use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum AgentRole {
    Planner,
    DomainSpecialist,
    Skeptic,
    Verifier,
    Other(String),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentManifest {
    pub id: String,
    pub name: String,
    pub description: String,
    pub role: AgentRole,
    pub capabilities: Vec<String>,
    pub required_context: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentInvocation {
    pub agent_id: String,
    pub task: String,
    pub context: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResult {
    pub output: Value,
    pub generated_claims: Vec<String>, // IDs of claims generated by the agent
}
